### ISSUE TITLE
Add i18n support for "Submit" page

### ISSUE THREAD

**Issue by pfefferle** [aaronpk/IndieNews#18]
The submit page has still a lot of untranslated texts: http://news.indiewebcamp.com/de/submit

**Comment by aaronpk** [comment]
Yes, I added a bunch of new strings to the Locale file, feel free to submit translations! https://github.com/aaronpk/IndieNews/blob/master/Locale/de/default.po

**Comment by pfefferle** [comment]
Done https://github.com/aaronpk/IndieNews/pull/19

thanks @diplix
