### ISSUE TITLE
submitting a german article doesn’t work

### ISSUE THREAD

**Issue by diplix** [aaronpk/IndieNews#20]
it’s there: http://webmention.io/api/mentions?target=http://news.indiewebcamp.com/de
but not showing up: http://news.indiewebcamp.com/de

**Comment by pfefferle** [comment]
I re-send the request with curl and it worked... Perhaps you forgot to add the syndication links, or something similar, on the first request...

**Comment by pfefferle** [comment]
Congrats for the first mention on IndieNews germany btw :smile:

**Comment by aaronpk** [comment]
How did it get to webmention.io? IndieNews and webmention.io have nothing to do with each other. Did you send the first webmention to webmention.io instead of IndieNews?

**Comment by diplix** [comment]
good question. i’m afraid i can’t answer. i pinged (webmentioned) only http://news.indiewebcamp.com/de and when it didn’t show up checked the sourcecode where i read
```
     <link rel="pingback" href="https://webmention.io/webmention?forward=http://news.indiewebcamp.com/de/webmention" />
  <link rel="webmention" href="http://news.indiewebcamp.com/de/webmention" />
```
so i querieed webmention.io, where i saw it my article being listed.
