### ISSUE TITLE
indiewebcamp.com => indieweb.org

### ISSUE THREAD

**Issue by snarfed** [aaronpk/IndieNews#26]
eg on https://news.indieweb.org/how-to-submit-a-post

feel free to close if you're tracking all these renames elsewhere!

**Comment by snarfed** [comment]
also in the error messages for when the backlink isn't found, etc

**Comment by aaronpk** [comment]
Thanks! This should be fixed in 5f828f3c13ee063a9bd0c381840fcd257b02714d
