### ISSUE TITLE
Add support for mp-syndicate-to

### ISSUE THREAD

**Issue by sebsel** [aaronpk/IndieNews#29]
Right now it looks for u-syndication or u-category, but mp-syndicate-to is probably the proper way of doing it now.

**Comment by aaronpk** [comment]
mp-syndicate-to is the command a micropub client sends to the server, but wouldn't ever show up in the microformats on the post. The current u-syndication and u-category is correct. Note that syndicating to indienews is done differently than a micropub client telling a server to syndicate a post. In this case it's more like the syndication is happening via webmention

**Comment by sebsel** [comment]
Oh you're totally right! I am abusing it for Bridgy Publish, which is with webmention too, but I forgot I am the one abusing things here :)
