### ISSUE TITLE
Seems to still be following old implied p-name rules

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/IndieNews#40]
My page didn't have a p-name on it, and X-ray correctly parses my post as a bookmark with no name, but IndieNews seems to have done an implied p-name to grab all the content inside of my h-entry making for a messy looking post rather than having a link to the original article.

Probably either needs updated logic or needs to use the current xray version.

**Comment by aaronpk** [comment]
This should be fixed with the updated xray version now
