### ISSUE TITLE
Fix bookmarks with commentary

### ISSUE THREAD

**Issue by gRegorLove** [aaronpk/IndieNews#48]
@jalcine's [bookmark](https://news.indieweb.org/en/anildash.com/2019/12/10/link-in-bio-is-how-they-tried-to-kill-the-web/) also included commentary with a `p-name`, so that got displayed instead of the bookmarked post's name. For bookmark posts, maybe it should first try to use the `p-name` within the `bookmark-of`.

**Comment by aaronpk** [comment]
This is by design, so that you can submit a post with your own commentary
