### ISSUE TITLE
`u-category` seems no longer working

### ISSUE THREAD

**Issue by pfefferle** [aaronpk/IndieNews#50]
The spec says, that it supports `u-category`:

```
<a href="https://news.indieweb.org/en" class="u-category">#indienews</a>
```

But when I try to publish `https://notiz.blog/2020/09/10/wp-meetup-stuttgart-indieweb-und-wordpress/`

I receive: `no_link_found`

**Comment by pfefferle** [comment]
See also: https://chat.indieweb.org/dev/2020-09-21/1600689077792800 /cc @frankmeeuwsen

**Comment by frankmeeuwsen** [comment]
I just tested the original URL from september, to submit it to Indienews. This time it worked (https://news.indieweb.org/nl/diggingthedigital.com/een-sociaal-netwerk-via-je-nieuwsbrief-en-eigen-site/). So I wrote a [new blogpost](https://diggingthedigital.com/indienews-werkt-weer/) to try it one more time. But this time I got a new error message, see below screenshot. I have no idea what to do now. /cc @pfefferle 


![Screenshot](https://dsc.cloud/triggi/CleanShot-2020-10-14-at-20.45.09-2x.png)

**Comment by aaronpk** [comment]
Well I should probably turn off the detail debug messages but in this case it's very helpful. It looks like the date you have for the `published` property is spelled out in text rather than being an ISO date like `2020-10-14`.

**Comment by pfefferle** [comment]
@aaronpk but my date should be fine!?!

**Comment by frankmeeuwsen** [comment]
@aaronpk OK, but then why would it accept another post from my blog? Compare the microformat from [the accepted URL](http://pin13.net/mf2/?url=https%3A%2F%2Fdiggingthedigital.com%2Feen-sociaal-netwerk-via-je-nieuwsbrief-en-eigen-site%2F) with the [rejected one](http://pin13.net/mf2/?url=https%3A%2F%2Fdiggingthedigital.com%2Feen-sociaal-netwerk-via-je-nieuwsbrief-en-eigen-site%2F). I might need to figure out how to change this in WordPress though...

**Comment by sebsel** [comment]
I think I just fixed the date-issue in a PR.

**Comment by pfefferle** [comment]
It seems that XRay simplifies the `u-category` to use the value instead of the URL: https://xray.p3k.app/parse?url=https%3A%2F%2Fnotiz.blog%2F2020%2F10%2F05%2Fblocktober%2F&pretty=true

**Comment by pfefferle** [comment]
But XRay seems to only find `p-category` and not `u-category`.

**Comment by aaronpk** [comment]
Oh did I misunderstand the issue? In any case yes let's discuss over on XRay

**Comment by aaronpk** [comment]
@pfefferle I just realized what's happening with your post... XRay is asking for the mf2 json version and that version doesn't have the URL categories in it.

Try this:

```
curl -H "Accept: application/mf2+json" https://notiz.blog/2020/10/05/blocktober/
```

**Comment by pfefferle** [comment]
I will either remove the feed or add the categories. Thanks!
