### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by kristofzerbe** [aaronpk/IndieNews#52]
It would be awesome if I could subscribe to the IndieNews via a feed reader. Title would be enough...

**Comment by sknebel** [comment]
There is an Atom feed marked up, so your feedreader should find it, otherwise here's the direct link: https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fnews.indieweb.org%2Fen

**Comment by kristofzerbe** [comment]
Uhh, yes ... Thanks a lot
