### ISSUE TITLE
Location/Language support

### ISSUE THREAD

**Issue by pfefferle** [aaronpk/IndieNews#6]
What du you think about language support? I (for example) blog mostly in german and so it may not be useful if I post to the "global" news stream.

**Comment by aaronpk** [comment]
Interesting, would it make sense to have multiple home pages, so people can submit to the German feed separately from the English feed? I'm strongly considering dropping the whole upvote/ranking concept and switching to just a time-ordered feed of entries, and this seems like a natural fit for that model.

**Comment by pfefferle** [comment]
I think it make sense to split different languages, because otherwise it can make the system very noisy.

**Comment by aaronpk** [comment]
Sounds good. I think what I'll do is add a top-level path (`/de`) for other languages, and to submit there you'd send a webmention to the German home page instead of the English home page.

**Comment by pfefferle** [comment]
Let me know if you need someone for translations...

**Comment by aaronpk** [comment]
Just to post an update on this, I've removed the whole upvoting/ranking thing, so the home page is just a chronological list of submissions. I also closed out all the other tickets. One step closer to getting to work on this!

**Comment by aaronpk** [comment]
@pfefferle Would you mind filling this out? Luckily there's not a lot of text on the site! I still need to do the date localization but then it should be ready!

https://github.com/aaronpk/IndieNews/blob/i18n/Locale/de/default.po

Please send a PR against the i18n branch. Thanks!

**Comment by pfefferle** [comment]
done :wink:

**Comment by aaronpk** [comment]
Thanks for the translation! This is live now! See http://news.indiewebcamp.com for more!
