### ISSUE TITLE
Submission form incorrectly throwing syndication link error

### ISSUE THREAD

**Issue by lazaruscorporation** [aaronpk/IndieNews#63]
I'm trying to submit my post at https://www.lazaruscorporation.co.uk/blogs/artists-notebook/posts/nsfw-on-the-indieweb through https://news.indieweb.org/en/submit

The form returns an error saying "Could not find a syndication or category link for this entry to news.indieweb.org."

However the syndication link is present, and is found by indiewebify.me - https://indiewebify.me/validate-h-entry/?url=https%3A%2F%2Fwww.lazaruscorporation.co.uk%2Fblogs%2Fartists-notebook%2Fposts%2Fnsfw-on-the-indieweb

**Comment by aaronpk** [comment]
This was a bug where IndieNews was finding your rel=alternate activity+json feed and using that instead of the microformats. I fixed it to only look at the microformats now and submitted your post to confirm.

**Comment by lazaruscorporation** [comment]
Thanks, Aaron!
